// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20210119213540_ReviewTest")]
    partial class ReviewTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Rating");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "New Zealand",
                            Rating = "5 Stars"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "France",
                            Rating = "4 Stars"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Somalia",
                            Rating = "1 Star"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Antartica",
                            Rating = "2 Stars"
                        });
                });

            modelBuilder.Entity("TravelApi.LocationReview", b =>
                {
                    b.Property<int>("LocationReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LocationId");

                    b.Property<int>("ReviewId");

                    b.HasKey("LocationReviewId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReviewId");

                    b.ToTable("LocationReview");
                });

            modelBuilder.Entity("TravelApi.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<int>("LocationId");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Body = "Great hiking and backpacking! Beautiful country!",
                            LocationId = 1,
                            UserName = "Patrick"
                        },
                        new
                        {
                            ReviewId = 2,
                            Body = "So much history and art! People are kinda rude though.",
                            LocationId = 2,
                            UserName = "Sarah"
                        },
                        new
                        {
                            ReviewId = 3,
                            Body = "Very very cold but pretty",
                            LocationId = 4,
                            UserName = "Bobby"
                        });
                });

            modelBuilder.Entity("TravelApi.LocationReview", b =>
                {
                    b.HasOne("TravelApi.Location", "Location")
                        .WithMany("JoinEntries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelApi.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelApi.Review", b =>
                {
                    b.HasOne("TravelApi.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
